version: '3.8'
services:
  app: 
    build: './' 
    image: olx-app
    container_name: olx-app
    # restart: always
    ports:
      - 3000:3000
    env_file:
      - .env_deployment
  db:
    image: postgres:13
    container_name: postgres
    # restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 123
      POSTGRES_DB: olxclone
  